kind: pipeline
name: default

steps:
- name: tickets
  image: laradock/workspace:2.2-7.2
  commands:
  - sleep 30
  - php -v
  - composer -V
  - cp .env.example .env
  - composer install --prefer-dist
  - php artisan key:generate
  - php artisan migrate
  - ./vendor/bin/phpunit

- name: ssh
  image: appleboy/drone-ssh
  host: mirorauhala.fi
  username: drone
  settings:
    password:
      from_secret: ssh_password
  port: 22
  script:
  - cd /var/www/tickets
  - git pull
  - ./deploy.sh
  trigger:
    branch:
    - develop
services:
- name: database
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tickets
