kind: pipeline
name: default

steps:
- name: tickets
  image: laradock/workspace:2.2-7.2
  commands:
    - sleep 30
    - php -v
    - composer -V
    - cp .env.example .env
    - composer install --prefer-dist
    - php artisan key:generate
    - php artisan migrate
    - ./vendor/bin/phpunit

- name: ssh
  image: appleboy/drone-ssh
  host: mirorauhala.fi
  username: drone
  secrets: [ SSH_DRONE_PASS ]
  port: 22
  script:
    - echo hello
    - echo world

services:
- name: database
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tickets
