kind: pipeline
name: default

steps:
- name: tickets
  image: laradock/workspace:2.2-7.2
  commands:
  - sleep 30
  - php -v
  - composer -V
  - cp .env.example .env
  - composer install --prefer-dist
  - php artisan key:generate
  - php artisan migrate
  - ./vendor/bin/phpunit

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: mirorauhala.fi
    username: drone
    port: 22
    script:
      - cd /var/www/tickets
      - touch hasthisbeenrun
      - git pull
      - php artisan down
      - composer install
      - php artisan migrate:refresh
      - php artisan db:seed
      - php artisan config:cache
      - php artisan view:cache
      - php artisan optimize
      - php artisan up
    password:
      from_secret: ssh_password
  trigger:
    branch:
    - develop
services:
- name: database
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tickets
