kind: pipeline
name: default

steps:
- name: tickets
  image: laradock/workspace:2.2-7.2
  commands:
    - php -v
    - composer -V
    - cp .env.example .env
    - composer install --prefer-dist
    - php artisan key:generate
    - php artisan migrate
    - ./vendor/bin/phpunit

services:
- name: database
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
