name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run unit testing
      run: |
        sudo apt install php-fpm php-gd php-xml php-zip unzip -yy
        wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
        composer
        ./vendor/bin/phpunit
        
